CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login       VARCHAR(255),
    full_name   VARCHAR(255),
    user_status VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS task
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    description    VARCHAR(255),
    responsible_id BIGINT,
    status         VARCHAR(255),
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_RESPONSIBLE FOREIGN KEY (responsible_id) REFERENCES users (id);


INSERT INTO users (login, full_name, user_status)
VALUES ('user1_login', 'User1 Full Name', 'Offline'),
       ('user2_login', 'User2 Full Name', 'Online'),
       ('user3_login', 'User3 Full Name', 'Online'),
       ('user4_login', 'User4 Full Name', 'Online'),
       ('user5_login', 'User5 Full Name', 'Online'),
       ('user6_login', 'User6 Full Name', 'Online'),
       ('user7_login', 'User7 Full Name', 'Online'),
       ('user8_login', 'User8 Full Name', 'Online'),
       ('user9_login', 'User9 Full Name', 'Online'),
       ('user10_login', 'User10 Full Name', 'Online'),
       ('user11_login', 'User11 Full Name', 'Online');

INSERT INTO task (name, description, responsible_id, status)
SELECT 'Task ' || generate_series,
       'Description for task ' || generate_series,
       (floor(random() * 10) + 1)::int,
       'Open'
FROM generate_series(1, 10000);

